### ISSUE TITLE
Evil corp katas from step 5 onwards are empty files

### ISSUE THREAD

**Issue by VitalyOlegovic** [Gianfrancoalongi/incremental_katas#2]
Somehow, the files from step 5 onwards are empty.

**Comment by artkpv** [comment]
They are supposed to be empty if a kata stops early. See readme

**Comment by Gianfrancoalongi** [comment]
This is correct as stated by @artkpv

**Comment by Gianfrancoalongi** [comment]
No issue. Some katas end early.
